### PR TITLE
very generic exception handling added to monitoring.py

### PR DESCRIPTION
**Pull request by bg002h**
Is this a pull request to the real blocksat-cli?

tiny additions to lines 147-149 of monitoring.py to catch any exception and handle it identically to the connection error handler.

### CODE REVIEW

**Comment by bg002h** [comment]
In testing...this code passes the "simply pulling network cable" test while original code crashed. I'm running reporting again now and will see if other errors cause it to crash or if this generic fix does the trick.

**Comment by bg002h** [comment]
This doesn’t work. Now the program simply hangs instead of exiting…doesn’t resume reporting or logging.

**Comment by blockstreamsatellite** [comment]
Hi @bg002h , 

In this case, it would be nice to add the `--log-scrolling --log-file` options to the command you are running. Then, you can take a look at the generated log file (saved at `~/.blocksat/logs/`) to see if anything is logged there. It would be interesting to understand what is causing the program to hang.

Let us know. Thanks!

**Comment by bg002h** [comment]
I’ll run it again like that. From what I recall, it prints a message about network issues or server down or something like that. I’ve been running it for a few days now without —report and have had no issues.

**Pull request closed without merging**
